# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20180927_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_start_time',
            field=models.DateTimeField(),
        ),
    ]
