# Generated by Django 2.0.5 on 2018-09-30 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20180929_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchcomments',
            name='rating',
        ),
        migrations.AddField(
            model_name='userprivatenotes',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprivatenotes',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
